Add blog files for ksql-connect
Platformatory/blog pull request #1
Opened 2022-05-30 19:27 UTC by srikanth-platformatory

Added all files for Blogpost - End to End data pipeline using Kafka Connect and ksqlDB.

2022-05-31 10:10 UTC, p6 requested changes
Can you undo your changes here?

2022-05-31 10:14 UTC, p6 reviewed
Embed the video as well.

2022-05-31 10:14 UTC, p6 commented on _posts/2022-05-30-KafkaConnect-ksqlDB-pipeline.md
> +A data pipeline is nothing but a chain or series of data processing steps. It starts off with ingestion of the data into the system, following which there are a series of steps, in which each step de
Delete. Everyone reading ths already knows what a data pipeline is.

2022-05-31 10:14 UTC, p6 commented on _posts/2022-05-30-KafkaConnect-ksqlDB-pipeline.md
> +So far, we have seen an end to end pipeline that will ingest records from a database into a kafka topic using Source connectors, process these records using ksqlDB, and finally dump these calculated
Can you write some next steps here? (perhaps it can be explored in another blog post)

- How this pipeline can be maintained in a code / repository
- How can you have a CI/CD process around it?
- How do you templatize the query

2022-05-31 10:15 UTC, p6 commented on _posts/2022-05-30-KafkaConnect-ksqlDB-pipeline.md
> +So far, we have seen an end to end pipeline that will ingest records from a database into a kafka topic using Source connectors, process these records using ksqlDB, and finally dump these calculated
Also, talk about how the KSQL pipeline can be monitored

2023-03-30 09:47 UTC, p6 commented
@ashwinvenkatesan229 - can you or @ashsridhar-platformatory take over this post? THis is KSQL + connect 101

2023-03-30 10:08 UTC, ashwinvenkatesan229 commented
Okay, I will look into this post and complete it

2023-07-20 08:40 UTC, closed without merging