Kafka performance metrics blog post.
Platformatory/blog pull request #5
Opened 2023-03-31 05:40 UTC by badri

TODO:
- [ ] paste screenshots
- [ ] articulate the testing loop

2023-07-15 17:56 UTC, p6 approved these changes

2023-07-17 10:47 UTC, p6-platformatory reviewed
@avinash-platformatory - can you look at this and sign off?
also address any pending gaps

2023-07-17 12:06 UTC, avinash-platformatory requested changes

2023-07-17 12:06 UTC, avinash-platformatory commented on _posts/2023-03-30-kafka-client-performance-metrics.md
> +[Apache Trogdor](https://github.com/apache/kafka/blob/trunk/TROGDOR.md) is a test framework for Kafka. Although it does excellent performance testing, Trogdor emphasizes a lot of [fault testing](http
Broken link for Apache Trogdor. Latest link - https://github.com/apache/kafka/tree/trunk/trogdor

2023-07-17 12:06 UTC, avinash-platformatory commented on _posts/2023-03-30-kafka-client-performance-metrics.md
> +1. No way to measure end to end latency. The [RoundTripWorkload](https://github.com/apache/kafka/blob/trunk/TROGDOR.md#roundtripworkload) is a close match for what we were looking for, but doesn’t qu
Broken link for Apache Trogdor. Latest link - https://github.com/apache/kafka/tree/trunk/trogdor#roundtripworkload

2023-07-17 12:06 UTC, avinash-platformatory commented on _posts/2023-03-30-kafka-client-performance-metrics.md
> +1. No way to measure end to end latency. The [RoundTripWorkload](https://github.com/apache/kafka/blob/trunk/TROGDOR.md#roundtripworkload) is a close match for what we were looking for, but doesn’t qu
Reason why RoundTripWorkload does not fit our goal is not clear. From the docs, it seems like it produces and consumes the same message, allowing to measure the e2e latency.

2023-07-17 12:06 UTC, avinash-platformatory commented on _posts/2023-03-30-kafka-client-performance-metrics.md
> +1. `kafka-topics` is the CLI tool which ships with your [confluent platform package](https://docs.confluent.io/platform/current/installation/installing_cp/zip-tar.html#prod-kafka-cli-install).
Probably worth mentioning that kafka-topics.sh ships with Apache Kafka

2023-07-17 12:06 UTC, avinash-platformatory commented on _posts/2023-03-30-kafka-client-performance-metrics.md
> +The Helm charts and the associated code mentioned in this post can be found [here](https://github.com/Platformatory/confluent-performance-suite).
The README for the repo is outdated and will be confusing for readers. There's mentions of S3, etc. Needs to be updated.

2023-07-17 15:07 UTC, p6-platformatory commented on _posts/2023-03-30-kafka-client-performance-metrics.md
> +The Helm charts and the associated code mentioned in this post can be found [here](https://github.com/Platformatory/confluent-performance-suite).
Please also rename the repository. It has nothing to do with confluent.

2023-07-18 04:54 UTC, badri commented
Raising a new PR as this is more than a yr old.

2023-07-18 04:54 UTC, closed without merging