E2e datapipeline
Platformatory/blog pull request #77
Opened 2024-12-19 11:57 UTC by Balaji632

Draft copy of E2E data pipeline using ORacle CDC Source and Redis Sink Connector.

2025-03-03 11:54 UTC, avinash-platformatory requested changes

2025-03-03 11:54 UTC, avinash-platformatory commented on _posts/2024-12-19-Stream-Oracle-DB-Changes-to-Redis-with-Confluent-Platform.md
> +&emsp;&emsp;&emsp;If any of the component isn’t up, you can start the individual container using command:
I think we can omit the docker compose troubleshooting commands

2025-03-03 11:54 UTC, avinash-platformatory commented on _posts/2024-12-19-Stream-Oracle-DB-Changes-to-Redis-with-Confluent-Platform.md
> +# Redis Sink Connector
Can you also include the need for a redis sink connector? Maybe include a few use cases where Oracle CDC data might be helpful in redis

2025-03-04 10:36 UTC, Balaji632 commented on _posts/2024-12-19-Stream-Oracle-DB-Changes-to-Redis-with-Confluent-Platform.md
> +&emsp;&emsp;&emsp;If any of the component isn’t up, you can start the individual container using command:
the reason for adding troubleshooting step is to ensure all containers are up and running. This is an additional information and might be useful for users who are new to data pipeline.

2025-04-22 08:47 UTC, Balaji632 commented on _posts/2024-12-19-Stream-Oracle-DB-Changes-to-Redis-with-Confluent-Platform.md
> +# Redis Sink Connector
done

2025-04-22 09:40 UTC, avinash-platformatory approved these changes

2025-04-22 10:44 UTC, merged